### ISSUE TITLE
Add news feed

### ISSUE THREAD

**Issue by mjf** [mseshachalam/x#1]
I would like to add the [8 hours](https://8hrs.xyz/) website to my news feed reader to track changes.

**Comment by malisetti** [comment]
What do you need, RSS/atom feed ? Let me know more details. I will see if I can implement it.

**Comment by malisetti** [comment]
you can the find feeds here
 
https://8hrs.xyz/feed/atom
https://8hrs.xyz/feed/rss

**Comment by mjf** [comment]
@mseshachalam Excellent, thank you!
